### ISSUE TITLE
Set the default dropdown for group to Default instead of Config

### ISSUE THREAD

**Issue by livesamarthgupta** [Satalink/omni-go#1]
### Subject of the feature
Set the default dropdown for group to Default instead of Config

Describe your issue here.
By default, the config dropdown is selected for groups, it would be much better if Default group is selected by default.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour
Set the default dropdown for group to Default instead of Config

What should happen?  Please describe the desired behaviour.
Set the default dropdown for group to Default instead of Config

### Alternatives
Has to select Default each time for entering a new entry.
What are the alternative solutions?  Please describe what else you have considered?

**Comment by Satalink** [comment]
fixed.  Thanks for the feedback!
